### ISSUE TITLE
Fix hobo not being able to DM users

### ISSUE THREAD

**Issue by experimatt** [jcardinal/hubot#6]
Hobo's not DMing the code of conduct when new users join, and if you DM hobo asking for the code of conduct, it doesn't actually send it to you.

See the comments below for some clues

**Comment by experimatt** [comment]
Per justin, this is the error when hobo tries to DM someone:
```error: Response not OK:  channel_not_found
Unhandled rejection Error: channel_not_found
  at handleHttpResponse (/home/ec2-user/hobo/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
  at handleTransportResponse (/home/ec2-user/hobo/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
  at apply (/home/ec2-user/hobo/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17)
  at wrapper (/home/ec2-user/hobo/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16)
  at Request.handleRequestTranportRes (/home/ec2-user/hobo/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
  at apply (/home/ec2-user/hobo/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17)
  at Request.wrapper [as _callback] (/home/ec2-user/hobo/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16)
  at Request.self.callback (/home/ec2-user/hobo/node_modules/request/request.js:186:22)
  at emitTwo (events.js:126:13)
  at Request.emit (events.js:214:7)
  at Request.<anonymous> (/home/ec2-user/hobo/node_modules/request/request.js:1060:10)
  at emitOne (events.js:116:13)
  at Request.emit (events.js:211:7)
  at IncomingMessage.<anonymous> (/home/ec2-user/hobo/node_modules/request/request.js:980:12)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:111:20)
  at IncomingMessage.emit (events.js:208:7)
  at endReadableNT (_stream_readable.js:1055:12)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by experimatt** [comment]
Some clues:
* https://github.com/slackapi/hubot-slack/issues/299
* https://github.com/slackapi/hubot-slack/issues/328
* https://github.com/slackapi/hubot-slack/issues/332

**Comment by experimatt** [comment]
Trying this...
`room = robot.adapter.client.rtm.dataStore.getDMByName msg.message.user.name`

**Comment by experimatt** [comment]
Fix: https://github.com/jcardinal/hubot/pull/10
